#!/usr/bin/env python3
"""Regenerate checked-in scene_shaders.h; requires glslc only at development time."""
from pathlib import Path
import struct
import subprocess
import tempfile

root = Path(__file__).resolve().parent
parts = ["/* Generated by shaders/generate.py. Do not edit. */\n#pragma once\n#include <stdint.h>\n"]
with tempfile.TemporaryDirectory() as temporary:
    for stage in ("vert", "frag", "mesh.vert", "mesh.frag", "surface.vert", "surface.frag", "image.frag", "present.frag", "shadow.vert", "shadow_surface.vert", "peel_mesh.frag", "peel_surface.frag", "depth.frag", "depth_surface.frag", "composite.frag", "translucent.frag", "glow.vert", "glow.frag", "glow_surface.frag", "fullscreen.vert", "glow_blur.frag", "glow_composite.frag"):
        output = Path(temporary) / (stage + ".spv")
        name = stage if "." in stage else "scene." + stage
        extra = []
        if stage == "peel_mesh.frag": name, extra = "mesh.frag", ["-DDEPTH_PEEL=1"]
        if stage == "peel_surface.frag": name, extra = "translucent.frag", ["-DDEPTH_PEEL=1"]
        subprocess.run(["glslc", *extra, "--target-env=vulkan1.1", "-O", str(root / name), "-o", str(output)], check=True)
        data = output.read_bytes()
        words = struct.unpack("<" + "I" * (len(data) // 4), data)
        parts.append("static const uint32_t worldr_scene_" + stage.replace(".","_") + "[] = {\n")
        for index in range(0, len(words), 8):
            parts.append("    " + ", ".join(f"0x{word:08x}" for word in words[index:index+8]) + ",\n")
        parts.append("};\n")
(root.parent / "scene_shaders.h").write_text("".join(parts))
